name: "Docker test"
description: "Test inputs"
author: "octocat@github.com"

inputs:
  X:
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
