name: workflow for greeting asma
on: push

jobs:
  build:
    name: asma action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          x: "Nice"
